AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firehose_transform_lambda
  SAM Template for firehose_transform_lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60 

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and 
    # SystemLogLevel or ApplicationLogLevel. Learn more here 
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Parameters:
  Subnet1A:
    Description: "VPC Private subnet id for us-east-1a"
    Type: "String"
    Default: "subnet-xxx"
  Subnet1B:
    Description: "VPC Private subnet id for us-east-1b"
    Type: "String"
    Default: "subnet-xxx"
  SecurityGroupDefault:
    Description: "Default Security Group"
    Type: "String"
    Default: "sg-xxx"
  CollectorEndpoint:
    Description: "OTEL Collector Endpoint"
    Type: "String"
    Default: "http://priv-collector-lb-xxx.elb.us-east-1.amazonaws.com:80/v1/metrics"

Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: helper-lambda-layer
      Description: Layer with Python dependencies
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
        - python3.11
        - python3.13
      RetentionPolicy: Retain
      PublishLambdaVersion: true


  FirehoseTransformFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      VpcConfig:
        SubnetIds:
          - !Ref Subnet1A
          - !Ref Subnet1B
        SecurityGroupIds:
          - !Ref SecurityGroupDefault
      Layers:
        - !Ref LambdaLayer
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
            Resource: "*"
      Environment:
        Variables:
          endpoint: !Ref CollectorEndpoint

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FirehoseTransformFunction:
    Description: Firehose Transform Lambda Function ARN
    Value: !GetAtt FirehoseTransformFunction.Arn

